In [1]:
import sqlite3
import pandas as pd
import numpy as np


In [2]:
con = sqlite3.connect('noroll_v3.5_2yrs.db')
no_roll = pd.read_sql('select fieldRA,fieldDec,night from observations;', con)
con.close()

In [3]:
con = sqlite3.connect('baseline_v3.5_2yrs.db')
baseline = pd.read_sql('select fieldRA,fieldDec,night from observations;', con)
con.close()

In [4]:
con = sqlite3.connect('four_cycle_v3.5_2yrs.db')
four = pd.read_sql('select fieldRA,fieldDec,night from observations;', con)
con.close()

In [5]:
no_roll['fieldRA']

0         200.782211
1         205.280457
2         208.768832
3         212.491654
4         209.531249
             ...    
462939    148.105306
462940    150.476965
462941    152.838116
462942    155.202097
462943    157.586821
Name: fieldRA, Length: 462944, dtype: float64

In [6]:
baseline['fieldRA']

0         200.782211
1         205.280457
2         208.768832
3         212.491654
4         209.531249
             ...    
462763    155.202097
462764    155.524410
462765    158.193299
462766    160.191096
462767    162.584715
Name: fieldRA, Length: 462768, dtype: float64

In [7]:
diff = no_roll['fieldRA'] - baseline['fieldRA']

In [8]:
np.where(np.abs(diff) > 0.1)

(array([245147, 245149, 245150, ..., 462765, 462766, 462767]),)

In [9]:
baseline["night"].values[np.where(np.abs(diff) > 0.1)]

array([374, 374, 374, ..., 730, 730, 730])

In [10]:
diff = four['fieldRA'] - baseline['fieldRA']

In [11]:
np.where(np.abs(diff) > 0.1)

(array([122087, 122088, 122089, ..., 462608, 462609, 462610]),)

In [12]:
baseline["night"].values[np.where(np.abs(diff) > 0.1)]

array([199, 199, 199, ..., 729, 729, 729])